# Introduction

Welcome to the pOmics Handbook! 




## Ressources

This is a brief listing of resources for proteomics data analysis and R programming on which all following content is based on:

-   [MaxQuant Summer School YouTube Channel](https://www.youtube.com/channel/UCKYzYTm1cnmc0CFAMhxDO8w)
-   More to come

This is merely a short list of general resources to start getting into proteomics data analysis in R. These and further articles, tutorial, etc. will be referenced throughout the handbook where informative. Have fun!


## Acknowledgements

This R package was developed at the University of Ottawa in the [lab](https://mysite.science.uottawa.ca/mberezov/) of [Dr. Maxim Berezovski](https://mysite.science.uottawa.ca/mberezov/maxim-berezovski.html) and working with [Dr. Zoran Minic](https://mysite.science.uottawa.ca/mberezov/team/current-lab-members/zoran-minic.html), Core Facility Manager and Biological Mass Spectrometrist of the [John L. Holmes Mass Spectrometry Facility](https://www.jlhms.uottawa.ca/staff.html). Both have given me the necessary challenges and freedom to try and learn approaches to various problems addressed by modern MS-based proteomics, and put the results together in this R package.

Initial collections of data analysis functions I used throughout my Master's program have been superseded by this package. My first undergraduate student Abdullah Khraibah motivated me to write functions comprehensible to others which ultimately led to much better code and reproducibility in my own work.

Last but not least, long before I used the tidyverse or R Markdown for the first time, [Daniel Torka](https://github.com/danielbenjamintorka), a friend and fellow student from Darmstadt, recommended both to me, which I dismissed at that time. Now, both are integral parts of my everyday work and I feel very stupid. Thanks Junior!



