# Introduction

Welcome to the pOmics Handbook. 

## Setup R and RStudio

First, we need to setup the environment in which we will work. For this, we need the [R programming language and statistical environment](https://www.r-project.org/), [RStudio](https://www.rstudio.com/), the most commonly used code editor for R, and finally a bunch of R packages, collections of readily available functions written by the R community. 

You can find a comprehensive introduction to those past [here](https://moderndive.netlify.app/1-getting-started.html).


## Learn R Basics

While there are many introductions to R out in the internet like [R for Data Science](https://r4ds.had.co.nz/introduction.html), the [swirl](https://swirlstats.com/) package, some introductions from [Modern Dive](https://moderndive.netlify.app/index.html), and other resources you can find on the official website of the [bookdown](https://bookdown.org/) package, this chapter might be filled with tips that help users getting start coding in R.


## Project management with Git and GitHub

In principle, we have enough tools at hand to get start with out analysis. 




